* What is Prowl?
Prowl is the Growl client for iOS. Push to your iPhone, iPod touch, or iPad notifications from a Mac or Windows computer, or from a multitude of apps and services. Easily integrate the Prowl API into your applications.
Visit [[http://prowlapp.com][Prowl app]] for more information.

** Requirements
1. An iPhone/iPad/iPod with the Prowl App installed.
1. Your api key from prowlapp.com
1. Love of FuelPhp framework

** Installation
Standard FuelPHP package installation: download the package and copy it to your fuelPHP packages folder: new_web_site/fuel/packages/ Open your config file (new_web_site/fuel/app/config/config.php) and look around line 187 and add 'Prowl' to the packages array.

** Usage
Add one of the following blocks of code to a controller file:
eg: new_web_site_/fuel/app/classes/controller/welcome.php

#+BEGIN_EXAMPLE
public function action_prowl()
{
	$p = Prowl::forge();
	$p->application('Name');
	$p->priority('2');
	$p->action('http://google.co.za');
	$p->subject('Subject');
	$p->message('Prowl is cool');
	$p->key('yourProwlApiKey');
	$p->push();
}
#+END_EXAMPLE

or

#+BEGIN_EXAMPLE
public function action_prowl()
{
	$config = array(
		'application' => 'application',
		'priority' => '1',
		'action' => 'http://google.co.za',
		'subject' => 'subject',
		'message' => 'testing 123',
		'key' => 'yourProwlApiKey',
		'url' => 'https://api.prowlapp.com/publicapi/add'
	);

	Prowl::push($config);
}
#+END_EXAMPLE

or if you have edited the config file

#+BEGIN_EXAMPLE
public function action_prowl()
{
	Prowl::push('quick send');
}
#+END_EXAMPLE

Then visit the url: http://fuelSetup/index.php/welcome/prowl

** Configuration
The package will accept the following in its config array:
#+BEGIN_EXAMPLE
$key = string/array : required
$application = string : required
$subject = string : required
$message = string : required
$action = valid url string
$priority = string (-2,-1,0,1,2)
$url = string
#+END_EXAMPLE
